task1
zzomg/SETI_5th_semester pull request #1
Opened 2020-09-20 08:54 UTC by zzomg

2020-09-20 14:00 UTC, Aloomenon requested changes
Почему сокеты нужно закрывать?

2020-09-22 10:22 UTC, zzomg commented
Если мы забиндили сокет на какой-то из портов и потом не закрыли его, он продолжает занимать этот порт и его не получится переиспользовать.

2020-09-23 06:18 UTC, zzomg commented
@Aloomenon

2020-09-24 15:57 UTC, Aloomenon commented
тэкс, а почему не закрываем их тогда?

2020-09-25 11:01 UTC, zzomg commented
@Aloomenon да, действительно. Вроде поправила

2020-09-25 13:47 UTC, Aloomenon commented
Окей, с этим разобрались. Расскажите мне про механизм мониторинга нестандартного завершения приложения, например коммандой kill. Достаточно просто про него написать.

2020-09-29 10:11 UTC, zzomg commented
> Окей, с этим разобрались. Расскажите мне про механизм мониторинга нестандартного завершения приложения, например коммандой kill. Достаточно просто про него написать.

@Aloomenon как я понимаю для этого можно использовать shutdown hook, то есть мы создаем отдельный поток который начнет свое исполнение во время аварийного завершения jvm (как раз например сигналов kill, кроме sigkill). внутри метода run в этом потоке мы корректно завершаем работу программы (interrupt'им, join'им еще исполняемые треды). можно создать несколько хуков, но при этом порядок их исполнения не определен.

2020-09-30 11:45 UTC, zzomg commented
@Aloomenon

2020-09-30 11:50 UTC, Aloomenon commented
Окей. Имя и фамилию скажите

On Wed, 30 Sep 2020, 18:46 Виктория, <notifications@github.com> wrote:

> @Aloomenon <https://github.com/Aloomenon>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/zzomg/SETI_5th_semester/pull/1#issuecomment-701338447>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGF7IC27PEYGA3I6A6BDJ7TSIMK7PANCNFSM4RTQTRCQ>
> .
>

2020-09-30 12:00 UTC, zzomg commented
@Aloomenon Кригер Виктория

2020-10-03 10:27 UTC, merged