task3 tree chat
zzomg/SETI_5th_semester pull request #3
Opened 2020-11-09 17:33 UTC by zzomg

2020-11-09 17:33 UTC, zzomg commented
@Aloomenon

2020-11-12 09:20 UTC, zzomg commented
@Aloomenon

2020-11-14 09:21 UTC, Aloomenon requested changes
ПРоверьте освобождение ресурсов.

2020-11-14 09:21 UTC, Aloomenon commented on task3/src/TreeChat/Master/RecvMaster.java
> +                    case ACCEPT_CHILD_MESSAGE -> {
Зачем?

2020-11-14 09:21 UTC, Aloomenon commented on task3/src/TreeChat/Packet.java
> +        ObjectInputStream ois = new ObjectInputStream(new ByteArrayInputStream(recvPacket.getData()));
Кодировка?

2020-11-28 18:18 UTC, zzomg commented
@Aloomenon поправила освобождение ресурсов вроде. Кодировка utf-8 как defaultCharset говорит

2020-11-30 13:17 UTC, Aloomenon commented
ок принял

2020-11-30 16:38 UTC, merged